### ISSUE TITLE
DeepL has changed their pages, it is not working now

### ISSUE THREAD

**Issue by shenmufeng** [sinedie/SRT-DeepL-Translator#13]
Hi,
Thanks for the good tool based on selenium. But recently, DeepL has changed their page element, so it is not working now. Could you please update code accordingly?

Thanks a lot!

**Comment by sinedie** [comment]
Mmm, didnt notice it, this weekend i'll solve this issue. Thank you for raising this. :D

**Comment by sinedie** [comment]
Can't replicate, it works for me. What version are you using? version 8.9 should do it. To installing this version you can use `pip install srt-deepl` or clone the master

**Comment by shenmufeng** [comment]
Thanks, tried again and it seems working now. I guess I am using an old one
