### ISSUE TITLE
choose language error

### ISSUE THREAD

**Issue by alexmaehon** [sinedie/SRT-DeepL-Translator#21]
Not working suddenly from yesterday

Error:

File "/content/app.py", line 1379, in main
    delete_old=True,
  File "/content/app.py", line 264, in translate
    wrap_limit,
  File "/content/app.py", line 132, in translate
    self.choose_languages(lang_from, lang_to)
  File "/content/app.py", line 127, in choose_languages
    f"//button[@dl-test='translator-lang-option-{lang_to['lang'].lower()}-{lang_to['lang'].upper()}'] | //button[text()='{lang_to['description']}']",
  File "/content/app.py", line 50, in __init__
    WebDriverWait(driver, 60).until(lambda driver: find_element(*locator))
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/support/wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x564493741553 <unknown>
#1 0x56449342c183 <unknown>
#2 0x564493462619 <unknown>
#3 0x564493462831 <unknown>
#4 0x564493497087 <unknown>
#5 0x56449348001d <unknown>
#6 0x564493494d6c <unknown>
#7 0x564493480363 <unknown>
#8 0x56449345647c <unknown>
#9 0x564493457945 <unknown>
#10 0x5644937b19d0 <unknown>
#11 0x564493776a38 <unknown>
#12 0x56449377675c <unknown>
#13 0x564493776fc2 <unknown>
#14 0x5644937af71b <unknown>
#15 0x564493777221 <unknown>
#16 0x56449375a5b3 <unknown>
#17 0x564493780988 <unknown>
#18 0x564493780b1a <unknown>
#19 0x564493799a41 <unknown>
#20 0x7fb6e043c6db <unknown>

**Comment by sinedie** [comment]
Fixed in commit 2356aa7664c229ab468bab477ac6f8c82078b16b. And published in last release (0.9.1) also in pypi, so feel free to upgrade the package and tell if any issue persist.
