### ISSUE TITLE
can you add turkish lang?

### ISSUE THREAD

**Issue by ghost** [sinedie/SRT-DeepL-Translator#28]
can you add turkish lang it supported by deepl

**Comment by sinedie** [comment]
Done, in last commit, feel free to clone it and use it (wont update PyPi package yet cause it mess it versions numbers, and got to tested better

Also, [this repo](https://github.com/sinedie/SRTranslator) is an improved way translate subtitles and all future work is gonna be in there

**Comment by ghost** [comment]
@sinedie Firstly thanks for quick reply, the repo that mentioned just give time out error also I cloned this repo and cd into srt_deepl folder whichever py file I tried to open `just gave ImportError: attempted relative import with no known parent package` error may you help please?

**Comment by sinedie** [comment]
Ok... could you open the issue in the other repo? Ty.

Also, dont try to run it from inside the srt_deep folder. Just run "python -m srt_deepl -h" from folder outside.
